FROM node:18-alpine AS build
WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install --frozen-lockfile

COPY ./frontend ./
RUN npm run build

FROM node:18-alpine AS development
WORKDIR /app

COPY frontend/package.json frontend/package-lock.json ./
RUN npm install --frozen-lockfile

COPY ./frontend ./

EXPOSE 3000
CMD ["npm", "start"]

FROM nginx:alpine AS production

COPY --from=build /app/build /usr/share/nginx/html

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=3 \
  CMD wget -qO- http://localhost:80 || exit 1

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]